kind: "Service"
apiVersion: "v1"
metadata:
  name: external-mariadb-service
  namespace: project-generator-ns
spec:
  ports:
    -
      name: mariadb
      port: 3306
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: external-mariadb-service
  namespace: project-generator-ns
subsets:
  -
    addresses:
      -
        ip: 172.19.0.1
    ports:
      -
        port: 3306